### ISSUE TITLE
request feature: insert before child

### ISSUE THREAD

**Issue by 3cp** [aurelia-contrib/aurelia-portal-attribute#4]
```html
<div class="this is my target">
  <!-- I would like the portal injected here -->
  <div class="collapse-button"></div>
</div>
```

Use case: to control collpase-button dynamically based on injection:

```css
.collapse-button {
  display: none;
}

.injected-class + .collapse-button {
  display: inline-block;
}
```

Too bad css is not flexible to say "if collapse-button is before injected-class".

Update: I could not use `ref=""` because the target dom is not in same view model.
